import { Inter } from 'next/font/google'
import './globals.css'
import TailHeaderMenu from './comm/TailHeaderMenu'
import TailFooter from './comm/TailFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App K-digital',
  description: 'K-digital project : Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full max-w-screen-xl mx-auto">
        <TailHeaderMenu />
        <main>
          {children}
        </main>  
        <TailFooter />
      </body>
    </html>
  )
}
